fix(utils): allow underscores in parameters for arithmetic expressions
I have a use case where I'm using Impact Framework with Prometheus. Prometheus likes to name it's metrics using `snake_case`. This was causing my manifests to break. Below is a minimal manifest that would break

```yaml
name: minimal-underscore-example
description: example manifest to show underscore errors
tags:
initialize:
  plugins:
    utilization:
      path: "builtin"
      method: Divide
      config:
        numerator: "cgroup_cpu_user_seconds"
        denominator: "cgroup_cpu_total_seconds"
        output: "cpu/utilization"

tree:
  children:
    job7984064:
      defaults:
        grid/carbon-intensity: 100
      pipeline:
        observe:
        regroup:
        compute:
          - utilization
        inputs:
          - cgroup_cpu_total_seconds: 32.694612
            cgroup_cpu_user_seconds: 32.327209
```

Running that manifest gives the following output:

```
name: minimal-underscore-example
description: example manifest to show underscore errors
tags: null
initialize:
  plugins:
    utilization:
      path: builtin
      method: Divide
      config:
        numerator: cgroup_cpu_user_seconds
        denominator: cgroup_cpu_total_seconds
        output: cpu/utilization
execution:
  status: fail
  command: >-
    /Users/broarr/.local/share/mise/installs/node/22.13.0/bin/node
    /Users/broarr/src/s12y-dscov-sci/node_modules/.bin/if-run -m minimal.yml
    --debug
  environment:
    if-version: 1.0.0
    os: macOS
    os-version: '15.2'
    node-version: 22.13.0
    date-time: 2025-02-04T15:01:13.442Z (UTC)
    dependencies:
      - '@grnsft/if@1.0.0'
  error: >-
    MissingInputDataError: cgroup is missing from the input array, or has
    nullish value.
tree:
  children:
    job7984064:
      defaults:
        grid/carbon-intensity: 100
      pipeline:
        observe: null
        regroup: null
        compute:
          - utilization
        inputs:
          - cgroup_cpu_total_seconds: 32.694612
            cgroup_cpu_user_seconds: 32.327209
```

This commit slightly edits the regex for arithmetic parameters to allow for underscores. I also tried to test underscores as numeric separator as well. If this behavior is intentional I'd be happy to document it in the right place